POST http://localhost:8080/auth/registrations
Content-Type: application/json

{
  "email": "john@mail.com",
  "password": "Aa12345~"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "john@mail.com",
  "password": "Aa12345~"
}


###
POST http://localhost:8080/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQG1haWwuY29tIiwiZXhwIjoxNjE0MzQwMTU0fQ.fDEOLghd_HWGUC36yzmHZHt9KxSLQlkzDN-O0GTAg1M

{
  "name": "John",
  "email": "john@mail.com",
  "address": "Tel Aviv",
  "phone": "055-1234567"
}

###
GET http://localhost:8080/contact/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huQG1haWwuY29tIiwiZXhwIjoxNjE0MzQwMTU0fQ.fDEOLghd_HWGUC36yzmHZHt9KxSLQlkzDN-O0GTAg1M